/** Category values used in shop filters and URLs (matches DB `products.category`). */
export const SHOP_CATEGORIES = [
  'Alcohol',
  'Beverages',
  'Bread',
  'Brocade',
  'Canned',
  'Caribbean product',
  'Cosmetics',
  'Dairy And Tea',
  'Flours & Rice',
  'Fresh Produce',
  'Frozen foods',
  'Hair & Braiding',
  'Headtie',
  'Kente',
  'Lace',
  'Meat and Seafood',
  'Motherland',
  'Non food',
  'Ready-to-wear',
  'Snack',
  'Spices',
  'Wax',
] as const
